### ISSUE TITLE
dear sir ,according to your step,i has installde relevent package .but i meet some error.i do this"cd uav_frontier_exploration_3d/scripts/startup ",and do "./start.sh"

### ISSUE THREAD

**Issue by xiecuijuan** [larics/uav_frontier_exploration_3d#2]
RLException: [sim_vehicle.launch] is neither a launch file in package [ardupilot_gazebo] nor is [ardupilot_gazebo] a launch file name
The traceback for the exception was written to the log file

jojo@jojo-INVALID:~/uav2_ws/src/uav_frontier_exploration_3d/scripts/startup$ waitForRos; rosparam set use_sim_time true; roslaunch ardupilot_gazebo mavros.launch config_file:=custom_config/apm_config.yaml
RLException: [mavros.launch] is neither a launch file in package [ardupilot_gazebo] nor is [ardupilot_gazebo] a launch file name
The traceback for the exception was written to the log file

i try to add the environment variable to my .bashrc file,but this way is not sovle my problem

**Comment by AnaBatinovic** [comment]
@xiecuijuan Please, check the issue [#1](https://github.com/larics/uav_frontier_exploration_3d/issues/1).
