### ISSUE TITLE
 where is the tmuxinator file

### ISSUE THREAD

**Issue by MrWhite928** [larics/uav_frontier_exploration_3d#4]
When I run ./ start.sh, error:./start.sh: Line 16: tmuxinator: Command not found

**Comment by AnaBatinovic** [comment]
@MrWhite928 Hi, did you solve this?  If not, please make sure you have tmuxinator installed.
As mentioned [here](https://github.com/tmuxinator/tmuxinator/issues/345), try to install it: `sudo gem install tmuxinator`
